# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
     - "4444:4444"
    networks:
     - exosuite-tests
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - exosuite-tests
    volumes:
      - /etc/hosts:/etc/hosts
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - exosuite-tests
    volumes:
      - /etc/hosts:/etc/hosts

  phantomjs:
    image: madhavajay/selenium-node-phantomjs
    depends_on:
      - selenium-hub
    environment:
      - PORT=5555
      - HUB=http://selenium-hub:4444
    networks:
      - exosuite-tests
    volumes:
      - /etc/hosts:/etc/hosts
    entrypoint: 'bash -c "phantomjs /home/phantomjs/ghostdriver/src/main.js --hub=$$HUB --port=$$PORT --ip=`hostname -I | cut -d\" \" -f1` --remoteHost=http://$$HOSTNAME:5555"'

networks:
  exosuite-tests:
      driver: bridge
